eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.url:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true
---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 81
